name: CI/CD Pipeline

on: push

# Specify two jobs: test and deploy

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.9'

      # Create venv and install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv 
          . venv/bin/activate
          pip install -r requirements.txt 

      # Initialize database schema
      - name: Set up db schema
        run: |
          . venv/bin/activate
          python init_db.py

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest tests/
    
