name: CI/CD Pipeline

on: push

# Specify two jobs: test and deploy

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.9'

      # Create venv and install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv 
          . venv/bin/activate
          pip install -r requirements.txt 

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest tests/

  deploy:
    if: success()
    runs on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        id: docker_build
        run: |
          docker build --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/taxfiler-app:latest .
          docker push ghcr.io/${{ github.repository_owner }}/taxfiler-app:latest
